#!/usr/bin/env python3
# created by Group Supermodels in VT2026
# for the course Modelling of Complex Systems at Uppsala University
# Group Members:
# Juan Rodriguez
# Björk Lucas
# Vootele Mets
# Marco Malosti
# Sofia Fernandes
# David Weingut

def parse_rle(rle_text):
    """
    Generated by ChatGPT for parsing RLE-encoded patterns.

    Parse an RLE-encoded Game of Life pattern and return a 2-D list of 0/1 values.

    Fixes vs. the original implementation
    ───────────────────────────────────────
    • Numeric '$' is handled correctly: '3$' advances 3 rows (inserts 2 blank rows).
    • Blank rows are no longer silently dropped.
    • Trailing dead cells within a row are no longer required; all rows in the
      returned grid are padded to the same width so add_pattern works uniformly.
    """
    # ── 1. Strip header / comment lines and join the data lines ──────────────
    data = ''
    for line in rle_text.splitlines():
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('x'):
            continue
        data += line
        if '!' in line:          # stop as soon as the terminator is seen
            break

    # ── 2. Parse character by character ──────────────────────────────────────
    rows   = []        # finished rows
    cells  = []        # cells accumulating for the current row

    i = 0
    while i < len(data):
        ch = data[i]

        # Collect a run-length prefix (may be absent → implicitly 1)
        count = 0
        while i < len(data) and data[i].isdigit():
            count = count * 10 + int(data[i])
            i += 1
        if count == 0:
            count = 1

        if i >= len(data):
            break

        ch = data[i]
        i += 1

        if ch == 'o':
            cells.extend([1] * count)
        elif ch == 'b':
            cells.extend([0] * count)
        elif ch == '$':
            # End current row, then insert (count - 1) additional blank rows.
            rows.append(cells)
            cells = []
            for _ in range(count - 1):
                rows.append([])
        elif ch == '!':
            break           # pattern terminator — stop parsing

    # Append the last row if it has any cells (pattern may omit the final '$')
    if cells:
        rows.append(cells)

    # ── 3. Pad all rows to the same width ─────────────────────────────────────
    if not rows:
        return rows
    width = max(len(r) for r in rows)
    rows  = [r + [0] * (width - len(r)) for r in rows]

    return rows