name: compile-second-report
run-name: Compile second report after push from ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tex'
  push:
    paths:
      - 'reports/L2/**'
      - '!reports/L2/src/main.pdf'
jobs:
    build-report:
      runs-on: ubuntu-latest
      steps:
        - name: Setup repo normally
          uses: actions/checkout@v6
          if: ${{ github.event_name != 'pull_request' }}
          with:
            token: ${{ secrets.DAVIDS_TOKEN }}
            persist-credentials: true
        - name: Setup repo for a PR
          uses: actions/checkout@v6
          with:
            ref: ${{ github.event.pull_request.head.ref }}
            persist-credentials: true
            token: ${{ secrets.DAVIDS_TOKEN }}
          if: ${{ github.event_name == 'pull_request' }}
        - name: compile
          uses: xu-cheng/latex-action@v4
          with:
            root_file: main.tex
            latexmk_use_xelatex: true
            latexmk_shell_escape: true
            working_directory: reports/L2/src
        - name: check for changes in pdf
          run: |
            git diff reports/L2/src/main.pdf | grep -q . || echo "should_commit=false" >> "$GITHUB_ENV"
        - name: add updated L2 PDF to github
          uses: EndBug/add-and-commit@v10
#         if: ${{ env.should_commit }}
          with:
            add: reports/L2/src/main.pdf
            message: "[skip actions] Automatic PDF compile, Lab 2"
